# Generated by Django 3.1.7 on 2021-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='age',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
