# Generated by Django 3.1.7 on 2021-08-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetectionApp', '0002_auto_20210808_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
